### PR TITLE
Fix netstandard2 version to work in 4.6.1 and fix ReferenceDomainAssemblies

### PR DESCRIPTION
**Pull request by seertenedos**
Basic change was to reverse a number of changes done to when porting to dotnet core as those changes were not needed with netstandard2.  Tests are passing on netcoreapp2.0 as well as a copy of the tests for net461.

Really related to AppDomain being added back in in netstandard2.0

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Hi Chris,

Thank you for the contribution.

Can you please provide some details so I can understand the nature of your changes. 

As far as I remember AppDomain was not available under NetStandard, at least at the time of the porting to .NETCore porting was performed. That's why I had to implement alternative approach with `AssemblyLoadContext` so the solution can work on ALL platforms. 

Your changes effectively reintroduce AppDoamin approach. Does it mean that NetStandard now offers AppDomain support? Did I just missed it? I remember that .NET Core guys were quite categorical about not going back to AppDomains. 

Thank you

**Comment by seertenedos** [comment]
Yea AppDomain was added as part of NetStandard2.0  they added a lot of things like that as so many people needed it to port their applications

**Comment by oleg-shilo** [comment]
That rather an excellent news. 
I was always irritated by such a dramatic inferiority of `AssemblyLoadContext` comparing to `AppDomain`.

Will also need to have a look at `Microsoft.CodeAnalysis.Scripting`. May be now it supports referencing file-less (in-memory) assemblies. I hope so... :)

**Comment by seertenedos** [comment]
oh there is one thing i should mention that i found acted a bit different and cause an issue. 
in  "public IEvaluator ReferenceAssembly(Assembly assembly) " i had add an null assembly check as now when you search for an assembly by partial name it sometimes returns a null and that broke other code.

**Comment by oleg-shilo** [comment]
Sure. Txs

**Comment by seertenedos** [comment]
i am not sure if it is auto match or not but is it possible to get this released in a new version as i am waiting on it for the conversion of our internal common libraries that feed into our projects.  trying to move everything to netstandard2 and run on 4.6.1 and core2

**Comment by oleg-shilo** [comment]
If you are happy with +your+ changes, I can just make a HotFix release with based on your PR. And I will proceed with reviewing the netstandard2 new features without a rush.

**Comment by seertenedos** [comment]
that would be great!

**Comment by oleg-shilo** [comment]
Done: 
```
Install-Package CS-Script.Core -Version 1.0.0.3-HotFix
```

**Comment by seertenedos** [comment]
thanks

**Pull request merged**
